# The Azure Queue Storage Source secret
apiVersion: v1
kind: Secret
metadata:
  name:  azure-queue-storage
type: Opaque
stringData:
  account_key: <ACCOUNT_KEY>

---

# The AWS Credentials secret
apiVersion: v1
kind: Secret
metadata:
  name: aws
type: Opaque
stringData:
  access_key_id: access_key_id
  secret_access_key: secret_access_key

---

# The Splunk Target secret
apiVersion: v1
kind: Secret
metadata:
  name: splunk-hec
data:
  token: <SPLUNK_TOKEN>
type: Opaque
