# The Azure Queue Storage Source
apiVersion: sources.triggermesh.io/v1alpha1
kind: AzureQueueStorageSource
metadata:
  name: sample
spec:
  accountName: csnfdemo
  queueName: triggermesh

  accountKey:
    valueFromSecret:
      name: azure-queue-storage
      key: account_key

  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: broker
      name: brkr

---

# The event source for our Aquasec events (SQS)
apiVersion: sources.triggermesh.io/v1alpha1
kind: AWSSQSSource
metadata:
  name: sample
spec:
  arn: <ARN>
  auth:
    credentials:
      accessKeyID:
        valueFromSecret:
          name: awscreds
          key: access_key_id
      secretAccessKey:
        valueFromSecret:
          name: awscreds
          key: secret_access_key
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: brkr

---

# The event source for our guardduty events (Service Bus Queue)
apiVersion: sources.triggermesh.io/v1alpha1
kind: AzureServiceBusQueueSource
metadata:
  name: sample
spec:
  queueID: <QUEUE_ID>
  auth:
    sasToken:
      connectionString:
        value: <CONNECTION_STRING>
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: brkr

---


# The Kafka Source
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: kafkasource
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "1"
    spec:
      containers:
        - image: gcr.io/triggermesh/kafkasource
          env:
          - name: CONFLUENT_BOOTSTRAP_SERVERS
            value: <BOOTSTRAP_SERVERS>
          - name: CONFLUENT_SASL_USERNAME
            value: <CONFLUENT_SASL_USERNAME>
          - name: CONFLUENT_SASL_PASSWORD
            value: <CONFLUENT_SASL_PASSWORD>
          - name: CONFLUENT_TOPIC
            value: <CONFLUENT_TOPIC>
          - name: K_SINK
            value: http://broker-ingress.knative-eventing.svc.cluster.local/default/brkr
---

# The Google Pub Sub Source
apiVersion: sources.triggermesh.io/v1alpha1
kind: GoogleCloudPubSubSource
metadata:
  name: gcp-pubsub-csnf
spec:
  topic: projects/security-sdbx/topics/triggermesh
  subscriptionID: triggermesh-sub
  serviceAccountKey:
    value: >-
      {
      <GOOGLE_SERVICE_ACCOUNT_KEY>
      }

  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: brkr
