
---

# The Azure Sentinel Target
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: hello-sentinel
spec:
  template:
    spec:
      containers:
        - image: gcr.io/triggermesh/azuresentineltarget:latest
          env:
          - name: AZURE_SUBSCRIPTION_ID
            value: <AZURE_SUBSCRIPTION_ID>
          - name: AZURE_RESOURCE_GROUP
            value: <AZURE_RESOURCE_GROUP>
          - name: AZURE_WORKSPACE
            value: <AZURE_WORKSPACE>
          - name: AZURE_CLIENT_SECRET
            value: <AZURE_CLIENT_SECRET>
          - name: AZURE_CLIENT_ID
            value: <AZURE_CLIENT_ID>
          - name: AZURE_TENANT_ID
            value: <AZURE_TENANT_ID>

---

# The Splunk Target
apiVersion: targets.triggermesh.io/v1alpha1
kind: SplunkTarget
metadata:
    name: splunk-distribution
spec:
    endpoint: <SPLUNK_ENDPOINT>
    skipTLSVerify: true
    token:
        valueFromSecret:
            key: token
            name: splunk-hec
