
# The Cloudguard CSNF event standardization transformation
apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: cloudguard-transformation
spec:
  context:
  - operation: add
    paths:
    - key: type
      value: io.triggermesh.csnf.cloudguard.transformation
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: brkr
  data:
  - operation: store
    paths:
    - key: $accountID
      value: data.additionalDetails.tenantId
    - key: $eventName
      value: data.additionalDetails.problemName
    - key: $eventShortDescription
      value: data.additionalDetails.problemDescription
    - key: $eventStartTime
      value: data.additionalDetails.firstDetected
    - key: $eventSeverity
      value: data.additionalDetails.riskLevel
    - key: $eventStatus
      value: data.additionalDetails.status
    - key: $resourceIdentifier
      value: data.additionalDetails.resourceId
    - key: $resourceType
      value: data.additionalDetails.resourceType
    - key: $resourceName
      value: data.additionalDetails.resourceName
    - key: $resourceRegion
      value: data.additionalDetails.region
    - key: $resourceZone
      value: data.compartmentName
    - key: $providerAccountId
      value: data.additionalDetails.tenantId
    - key: $resourceName
      value: data.additionalDetails.resourceName
    - key: $resourceName
      value: data.additionalDetails.resourceName

  - operation: delete
    paths:
    - key:

  - operation: add
    paths:
    - key: provider
      value: Oracle Cloud Infrastructure
    - key: providerType
      value: CSP
    - key: providerId
      value: $resourceName
    - key: source.sourceName
      value: Cloud Guard
    - key: source.sourceId
      value: none
    - key: provider.accountId
      value: $accountID
    - key: event.name
      value: $eventName
    - key: event.shortDescription
      value: $eventShortDescription
    - key: event.startTime
      value: $eventStartTime
    - key: event.severity
      value: $eventSeverity
    - key: event.status
      value: $eventStatus
    - key: resource.identifier
      value: $resourceIdentifier
    - key: resource.type
      value: $resourceType
    - key: resource.name
      value: $resourceName
    - key: resource.region
      value: $resourceRegion
    - key: resource.zone
      value: $resourceZone

---

# The Aquasec CSNF event standardization transformation
apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: aquasec-transformation
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: brkr
  context:
  - operation: add
    paths:
    - key: type
      value: io.triggermesh.csnf.aquasec.transformation
  data:
  - operation: parse
    paths:
    - key: data
      value: JSON
  - operation: store
    paths:
    - key: $id
      value: host
    - key: $hostid
      value: data.hostid
    - key: $reason
      value: data.reason
    - key: $time
      value: data.time
    - key: $containerid
      value: containerid
    - key: $category
      value: data.category
    - key: $container
      value: container
    - key: $region
      value: data.vm_location
    - key: $image
      value: image
    - key: $name
      value: type

  - operation: delete
    paths:
    - key:

  - operation: add
    paths:
    - key: provider
      value: Aquasec
    - key: providerId
      value: $hostid
    - key: provider.providerType
      value: aquasec
    - key: provider.providerId
      value: $id
    - key: provider.accountId
      value: $id
    - key: provider.name
      value: Google PubSub
    - key: source.sourceName
      value: Aquasec
    - key: source.sourceId
      value: $containerid
    - key: event.guid
      value: $hostid
    - key: event.name
      value: $name
    - key: event.shortDescription
      value: "an aquasec short description goes here"
    - key: event.startTime
      value: $time
    - key: event.severity
      value: HIGH
    - key: event.status
      value: OPEN
    - key: resource.identifier
      value: $id
    - key: resource.type
      value: Container
    - key: resource.name
      value: $hostid
    - key: resource.region
      value: us-1-c
    - key: resource.zone
      value: us
    - key: image
      value: $image

---

# The Azure Defender CSNF event standardization transformation
apiVersion: flow.triggermesh.io/v1alpha1
kind: Transformation
metadata:
  name: azure-defender-transformation
spec:
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: brkr
  context:
  - operation: add
    paths:
    - key: type
      value: io.triggermesh.csnf.azure.defender.transformation
  data:
  - operation: store
    paths:
    - key: $providerType
      value: Azure
    - key: $providerId
      value: Data.properties.compromisedEntity
    - key: $providerType
      value: Data.type
    - key: $sourceId
      value: Data.properties.vendorName
    - key: $providerAccountId
      value: Data.properties.subscriptionId
    - key: $eventGUID
      value: Data.properties.instanceId
    - key: $eventName
      value: Data.properties.alertName
    - key: $eventShortDescription
      value: Data.properties.description
    - key: $eventStartTime
      value: Data.properties.reportedTimeUtc
    - key: $eventSeverity
      value: Data.properties.reportedSeverity
    - key: $eventStatus
      value: Data.properties.state
    - key: $resourceIdentifier
      value: Data.id
    - key: $resourceType
      value: Data.type
    - key: $resourceName
      value: Data.properties.compromisedEntity


  - operation: delete
    paths:
    - key:

  - operation: add
    paths:
    - key: provider
      value:  Azure Defender
    - key: providerType
      value: $providerType
    - key: providerId
      value: $providerId
    - key: source.sourceName
      value: "Azure Defender"
    - key: source.sourceId
      value: $sourceId
    - key: provider.accountId
      value: $providerAccountId
    - key: event.guid
      value: $eventGUID
    - key: event.name
      value: $eventName
    - key: event.shortDescription
      value: $eventShortDescription
    - key: event.startTime
      value: $eventStartTime
    - key: event.severity
      value: $eventSeverity
    - key: event.status
      value: $eventStatus
    - key: resource.identifier
      value: $resourceIdentifier
    - key: resource.type
      value: $resourceType
    - key: resource.name
      value: $resourceName
    - key: resource.region
      value: us-east-1
    - key: resource.zone
      value: us
